apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-80y2
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-migj-tenant/rhtap-demo-app/hacbs-test-project-80y2@sha256:1bf071a1a3077b4eb4afe01244da1dbd2811e2c6d416cbfcc446004551cad30f
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
